# Generated by Django 4.1 on 2022-09-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLente', '0003_cotiza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.IntegerField(max_length=50),
        ),
    ]
