# Generated by Django 4.1 on 2022-09-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLente', '0004_alter_turno_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.IntegerField(),
        ),
    ]
