# Generated by Django 4.1 on 2022-09-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLente', '0005_alter_turno_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='dni',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.CharField(max_length=20),
        ),
    ]
