# Generated by Django 4.1.1 on 2022-10-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLente', '0008_rename_img_receta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
    ]
