# Generated by Django 4.1.1 on 2022-10-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLente', '0009_alter_receta_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
