# Generated by Django 4.1.1 on 2022-10-03 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLente', '0011_receta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
