# Generated by Django 4.1.1 on 2022-10-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLente', '0013_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
