# Generated by Django 4.1.1 on 2022-10-06 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLente', '0015_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
