# Generated by Django 4.1.1 on 2022-10-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLente', '0018_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
